Bot 3039 add timeout
CanalTP/NavitiaComponent pull request #36
Opened 2021-09-14 13:09 UTC by Fahmus

This PR add navitia timeout in config parameters

2021-09-14 14:08 UTC, dvdn commented on README.md
> +| `timeout`             | `int`      | Navitia timeout         |                    |  `6000`       |
```suggestion
| `timeout`             | `int`      | Navitia timeout (in ms) |                    |  `6000`       |
```

2021-09-15 09:50 UTC, pthegner requested changes
Same comment as #37

2021-09-21 06:53 UTC, pthegner approved these changes

2021-09-23 12:57 UTC, dvdn approved these changes

2021-09-23 12:57 UTC, merged