[Sf 2.8] Add navitia timeout in config parameters
CanalTP/NavitiaComponent pull request #37
Opened 2021-09-14 14:03 UTC by Fahmus

## Description

This PR add navitia timeout in config parameters

## Issue

Issue link: BOT-3039

2021-09-14 14:05 UTC, dvdn commented on README.md
> +| `timeout`             | `int`      | Navitia timeout         |                    |  `6000`       |
```suggestion
| `timeout`             | `int`      | Navitia timeout (in ms)        |                    |  `6000`       |
```

2021-09-14 14:58 UTC, dvdn commented on Service/NavitiaService.php
> +        $this->timeout = max($timeout, $this->config->getTimeout());
`max` is perhaps not the best option.
If you set less than 6000, your config won't be used.

2021-09-15 06:04 UTC, dvdn approved these changes

2021-09-15 09:45 UTC, pthegner requested changes

2021-09-15 09:45 UTC, pthegner commented on Service/NavitiaService.php
>      public function process($query, $format = null, $timeout = 6000, $pagination = true)
If you can override the config by passing a timeout to the function, you should do it.
This function is called by the serviceFacade (you should set the timeout to null by default and if null, used the config one).

2021-09-15 12:57 UTC, kun2985 approved these changes

2021-09-15 12:59 UTC, merged